"""initial schema

Revision ID: e2cf84d3406e
Revises: 
Create Date: 2026-03-01 14:33:44.170653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e2cf84d3406e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fencers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fencer_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['fencer_id'], ['fencers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('opponent_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=10), nullable=True),
    sa.Column('video_url', sa.String(length=1024), nullable=True),
    sa.Column('video_key', sa.String(length=1024), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=True),
    sa.Column('error', sa.String(length=2000), nullable=True),
    sa.Column('pipeline_progress', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opponent_id'], ['fencers.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bout_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['bout_id'], ['bouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bout_id', sa.Integer(), nullable=False),
    sa.Column('technique_scores', sa.JSON(), nullable=False),
    sa.Column('patterns', sa.JSON(), nullable=False),
    sa.Column('fatigue_markers', sa.JSON(), nullable=False),
    sa.Column('llm_summary', sa.String(length=8000), nullable=True),
    sa.Column('practice_plan', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bout_id'], ['bouts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bout_id')
    )
    op.create_table('frames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bout_id', sa.Integer(), nullable=False),
    sa.Column('timestamp_ms', sa.Integer(), nullable=False),
    sa.Column('fencer_pose', sa.JSON(), nullable=False),
    sa.Column('opponent_pose', sa.JSON(), nullable=True),
    sa.Column('action_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['bout_id'], ['bouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blade_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frame_id', sa.Integer(), nullable=False),
    sa.Column('tip_xyz', sa.JSON(), nullable=False),
    sa.Column('velocity_xyz', sa.JSON(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('flex_offset_xyz', sa.JSON(), nullable=True),
    sa.Column('nominal_xyz', sa.JSON(), nullable=True),
    sa.Column('correction_cost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['frame_id'], ['frames.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('frame_id')
    )
    op.create_table('kinetic_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frame_id', sa.Integer(), nullable=False),
    sa.Column('launch_readiness', sa.Float(), nullable=True),
    sa.Column('weight_distribution', sa.Float(), nullable=True),
    sa.Column('knee_angles', sa.JSON(), nullable=True),
    sa.Column('off_arm_orientation', sa.JSON(), nullable=True),
    sa.Column('spine_angle', sa.Float(), nullable=True),
    sa.Column('recovery_complete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['frame_id'], ['frames.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('frame_id')
    )
    op.create_table('threat_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frame_id', sa.Integer(), nullable=False),
    sa.Column('distance_to_nearest_target', sa.Float(), nullable=True),
    sa.Column('distance_to_optimal_target', sa.Float(), nullable=True),
    sa.Column('closing_velocity', sa.Float(), nullable=True),
    sa.Column('correction_angle', sa.Float(), nullable=True),
    sa.Column('correction_cost', sa.Float(), nullable=True),
    sa.Column('projected_arrival_xyz', sa.JSON(), nullable=True),
    sa.Column('attack_viability', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['frame_id'], ['frames.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('frame_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('threat_metrics')
    op.drop_table('kinetic_states')
    op.drop_table('blade_states')
    op.drop_table('frames')
    op.drop_table('analyses')
    op.drop_table('actions')
    op.drop_table('bouts')
    op.drop_table('sessions')
    op.drop_table('fencers')
    # ### end Alembic commands ###
